{% set name = "popmon" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/popmon-{{ version }}.tar.gz
  sha256: 7f9596683fd2c5abfb307a7fcb314bc9417777f9462e28708eea0ac0c54379e9

build:
  entry_points:
    - popmon_run = popmon.pipeline.amazing_pipeline:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - histogrammar >=1.0.30
    - htmlmin
    - jinja2
    - joblib >=0.14.0
    - numpy >=1.18.0
    - pandas >=0.25.1
    - phik
    - plotly >=5.8.0
    - pybase64 >=1.0.1
    - pydantic
    - python >=3.6
    - scipy >=1.5.2
    - tqdm
    - typing-extensions

test:
  imports:
    - popmon
  commands:
    - pip check
    - popmon_run --help
  requires:
    - pip

about:
  home: https://github.com/ing-bank/popmon
  summary: Monitor the stability of a pandas or spark dataset
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mepa
